# Generated by Django 5.2.6 on 2025-10-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.department"
            ),
        ),
    ]
