# Generated by Django 5.2.6 on 2025-10-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Instructor", "0001_initial"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.department"
            ),
        ),
    ]
