# Generated by Django 5.2.7 on 2025-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("instructor", "instructor"),
                    ("admin", "admin"),
                ],
                max_length=20,
            ),
        ),
    ]
