# Generated by Django 5.2.6 on 2025-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "CourseCode",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("CourseName", models.CharField(max_length=100)),
                ("CourseDesc", models.TextField()),
                ("CourseCredits", models.IntegerField()),
                ("Course_Dept_ID", models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
