# Generated by Django 5.2.7 on 2025-10-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Course_Dept_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="department.department",
            ),
        ),
    ]
