# Generated by Django 5.2.6 on 2025-10-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Instructor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_name", models.CharField(max_length=100)),
                (
                    "det_id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_led",
                        to="Instructor.instructor",
                    ),
                ),
            ],
        ),
    ]
