# Generated by Django 5.2.6 on 2025-10-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrolled", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolled",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrolled",
            unique_together={("student_id", "course_code")},
        ),
    ]
